services:
  webserver:
    environment:
      MOODLE_DOCKER_SSL: "true"
      MOODLE_SSLPROXY: "true"
      MOODLE_DOCKER_WEB_HOST: "rvc-vle-test.rvc.ac.uk"
      MOODLE_DOCKER_WEB_PROTOCOL: "https"
      MOODLE_DOCKER_WEB_PORT: "8443"
      MOODLE_DOCKER_SSL_OVERRIDE: "true"
    command: >
      sh -c "
        (while true; do php /var/www/html/admin/cli/cron.php; done) &
        apache2-foreground
      "
    volumes:
      - ${MOODLE_DOCKER_WWWROOT}:/var/www/html

  db:
    volumes:
      - moodledb_data:/var/lib/postgresql/data

volumes:
  moodledb_data:

networks:
  default:
    name: ${MOODLE_DOCKER_NETWORK:-moodle-docker_default}
