submodules:
  - name: Moodle
    url: https://github.com/moodle/moodle.git
    path: core/moodle
    branch: main
  - name: Moodle Docker
    url: https://github.com/moodlehq/moodle-docker.git
    path: core/moodle-docker
    branch: main
  - name: Elastic Search
    url: https://github.com/catalyst/moodle-search_elastic.git
    path: core/moodle/search/engine/elastic
    branch: MOODLE_310_STABLE
  - name: PostgresFullTextSearch
    url: https://github.com/catalyst/moodle-search_postgresfulltext.git
    path: core/moodle/search/engine/postgresfulltext
    branch: master
  - name: Azure Search
    url: https://github.com/catalyst/moodle-search_azure.git
    path: core/moodle/search/engine/azure
    branch: master
  - name: Amazon Local AWS SDK
    url: https://github.com/catalyst/moodle-local_aws.git
    path: core/moodle/local/aws
    branch: master
  - name: mAIci Moodle Chat Interface
    url: https://github.com/caiocarvalhofre/mod_maici.git
    path: core/moodle/mod/maici
    branch: main
  - name: Moodle Search Solr RAG
    url: https://github.com/mhughes2k/moodle-search_solrrag.git
    path: search/solrrag
    branch: main
  - name: Moodle Local AI
    url: https://github.com/mhughes2k/moodle-local_ai.git
    path: local/local_ai
    branch: main
database:
  - name: pgsql
