submodules:
  - name: Weiviate
    path: plugins/weiviate
    docker: "docker compose up -d"
  - name: Ollama
    path: plugins/ollama
    branch: main
    docker: "docker compose up -d"
use_nvidia: true
